### PR TITLE
HTML Search: Fix removal of unwanted anchor content from search results

### LINKED ISSUE #12320: Search summaries include unwanted anchor content
### Describe the bug

In the latest version of Sphinx, search summaries include the anchor (which is often a character which is not present in a font). Example snippit:

image

Note `F0C1` which is the paperclip character in the readthedocs theme

### How to Reproduce

This is easily reproducible with any version of Sphinx since https://github.com/sphinx-doc/sphinx/commit/bf0bec3b4b8c019acad4a77a9e228de4e65b538b, when the bug was introduced. Simply perform a search and note that anchor content is in the results.

### Environment Information

```text
(skipping since not needed)
```

### Sphinx extensions

```python
(skipping since not needed)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wlach**
Subject: Fix removal of unwanted anchor content from search results

### Feature or Bugfix

- Bugfix

### Purpose

This was accidentally broken in https://github.com/sphinx-doc/sphinx/commit/bf0bec3b4b8c019acad4a77a9e228de4e65b538b (https://github.com/sphinx-doc/sphinx/pull/12057), this just fixes it (and updates the existing test so it hopefully doesn't happen again).

### Detail

N/A

### Relates

Closes #12320

### CODE REVIEW

File: sphinx/themes/basic/static/searchtools.js [hunk 1]
```diff
@@ -178,7 +178,7 @@ const Search = {
 
   htmlToText: (htmlString, anchor) => {
     const htmlElement = new DOMParser().parseFromString(htmlString, 'text/html');
-    for (const removalQuery of [".headerlinks", "script", "style"]) {
+    for (const removalQuery of [".headerlink", "script", "style"]) {
```
Comment (wlach) [inline sphinx/themes/basic/static/searchtools.js:181]: This was (correctly) spelled `.headerlink` before.

**Comment by wlach** [comment]
@jayaddison @picnixz Can you take a look? Looks like an accidental regression from some previous work.

**Review by jayaddison — APPROVED** [review]
Yep, looks good to me - thanks @wlach!

File: CHANGES.rst [hunk 2]
```diff
@@ -25,6 +25,8 @@ Bugs fixed
 * #12162: Fix a performance regression in the C domain that has
   been present since version 3.0.0.
   Patch by Donald Hunter.
+* #12320: Fix removal of anchors from search summaries.
```
Comment (jayaddison) [inline CHANGES.rst]: Possibly also worth mentioning that this is a regression since 7.3.0 (comparing to the entry a couple of lines earlier).

Comment (wlach) [reply CHANGES.rst]: Yep, I'll add a note on that.

**Comment by AA-Turner** [comment]
Thanks Will!

Out of interest, would you be interested in triage permissions, to hopefully make your work on the search features easier?

A

**Comment by wlach** [comment]
> Out of interest, would you be interested in triage permissions, to hopefully make your work on the search features easier?

Yep, that'd be great! Thanks.
