### PR TITLE
search: order non-main index entries after other results

### LINKED ISSUE #11578: searchindex: non-main index entries scored too high
### Describe the bug

Since #10819, index entries are returned as search results.  When the query string exactly matches an indexed term, all index entries become search results with score 100.  This places them above most other search results.

Reporting "main" index entries early in the search results makes sense.  However, non-main index entries are often just arbitrary cross-references to the indexed term.  Currently these receive the same score as main index entries and are therefore ordered early in search results.  This obscures the main entries and other more-important matches such as document titles.

This problem affects CMake's documentation, and is tracked in [CMake Issue 25175](https://gitlab.kitware.com/cmake/cmake/-/issues/25175).  Here are some examples showing a search in CMake 3.27.1's documentation.

<details><summary>Using Sphinx 5.3.0 (click to expand screenshot):</summary>

cmake-3 27 1-sphinx-5 3 0

</details>

<details><summary>Using Sphinx 5.1.1 (click to expand screenshot):</summary>

cmake-3 27 1-sphinx-5 1 1

</details>

<details><summary>Using Sphinx 5.3.0 plus a patch that removes non-main index entries (click to expand screenshot):</summary>

cmake-3 27 1-sphinx-5 3 0-patch

The patch is for demonstration in this issue and is not a proposed fix:

```patch
diff --git a/sphinx/search/__init__.py b/sphinx/search/__init__.py
index 5330d7e7c..1741ff7ff 100644
--- a/sphinx/search/__init__.py
+++ b/sphinx/search/__init__.py
@@ -387,7 +387,7 @@ class IndexBuilder:
         index_entries: Dict[str, List[Tuple[int, str]]] = {}
         for docname, entries in self._index_entries.items():
             for entry, entry_id, main_entry in entries:
-                index_entries.setdefault(entry.lower(), []).append((fn2index[docname], entry_id))
+                index_entries.setdefault(entry.lower(), []).append((fn2index[docname], entry_id, main_entry))

         return dict(docnames=docnames, filenames=filenames, titles=titles, terms=terms,
                     objects=objects, objtypes=objtypes, objnames=objnames,
diff --git a/sphinx/themes/basic/static/searchtools.js b/sphinx/themes/basic/static/searchtools.js
index e89e34d4e..f4920587a 100644
--- a/sphinx/themes/basic/static/searchtools.js
+++ b/sphinx/themes/basic/static/searchtools.js
@@ -300,7 +300,7 @@ const Search = {
     // search for explicit entries in index directives
     for (const [entry, foundEntries] of Object.entries(indexEntries)) {
       if (entry.includes(queryLower) && (queryLower.length >= entry.length/2)) {
-        for (const [file, id] of foundEntries) {
+        for (const [file, id, main] of foundEntries.filter((fe) => fe[2] === "main")) {
           let score = Math.round(100 * queryLower.length / entry.length)
           results.push([
             docNames[file],
```

</details>

### How to Reproduce

This is difficult to reproduce in a small example because it requires a large number of documents to demonstrate non-trivial search results.

One can reproduce the problem by building CMake 3.27.1's documentation like this:

```console
$ curl -OL https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1.tar.gz
$ tar xvf cmake-3.27.1.tar.gz
$ cmake -S cmake-3.27.1/Utilities/Sphinx -B cmake-docs -DSPHINX_HTML=ON
$ cmake --build cmake-docs
$ x-www-browser 'cmake-docs/html/search.html?q=CMAKE_TOOLCHAIN_FILE'
```

This should show results similar to the description's screenshots.

### Environment Information

```text
Platform:              linux; (Linux-6.4.0-1-amd64-x86_64-with-glibc2.37)
Python version:        3.11.3 (main, Apr  5 2023, 00:00:00) [GCC 13.0.1 20230401 (Red Hat 13.0.1-0)])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.19
Jinja2 version:        3.0.3
```

### PR DESCRIPTION
**Pull request by bradking**
Since #10819, index entries are returned as search results. When the query string exactly matches an indexed term, all index entries become search results with score 100.  This places them above most other search results.

Reporting "main" index entries early in the search results makes sense, but non-main index entries are often just arbitrary cross-references to the indexed term.  Collect them in a separate group that is always placed after other results.  This avoids obscuring the main entries and other more-important matches such as document titles.

Fixes: #11578  
Supersedes: #11695

### CODE REVIEW

File: sphinx/themes/basic/static/searchtools.js [hunk 1]
```diff
@@ -284,16 +296,19 @@ const Search = {
     // console.info("required: ", [...searchTerms]);
     // console.info("excluded: ", [...excludedTerms]);
 
-    // array of [docname, title, anchor, descr, score, filename]
-    let results = [];
+    // Collect multiple result groups to be sorted separately and then ordered.
+    // Each is an array of [docname, title, anchor, descr, score, filename].
+    let normalResults = [];
```
Comment (picnixz) [inline sphinx/themes/basic/static/searchtools.js]:
```suggestion
    const normalResults = [];
```

File: sphinx/themes/basic/static/searchtools.js [hunk 2]
```diff
@@ -284,16 +296,19 @@ const Search = {
...
+    let nonMainIndexResults = [];
```
Comment (picnixz) [inline sphinx/themes/basic/static/searchtools.js]:
```suggestion
    const nonMainIndexResults = [];
```

File: sphinx/themes/basic/static/searchtools.js [hunk 3]
```diff
@@ -308,46 +323,51 @@ const Search = {
...
-    });
+    normalResults.sort(_orderResultsByScoreThenName);
+    nonMainIndexResults.sort(_orderResultsByScoreThenName);
+
+    // Combine the result groups in (reverse) order.
+    // Non-main index entries are typically arbitrary cross-references,
+    // so display them after other results.
+    let results = [];
+    results.push(...nonMainIndexResults);
+    results.push(...normalResults);
```
Comment (picnixz) [inline sphinx/themes/basic/static/searchtools.js]:
```suggestion
    let results = [...nonMainIndexResults, ...normalResults];
```
Note that the spread operator may limit the numbers of elements when used in a function call and there will be a stack error in `push` if there are more than 1E6 elements. While I think we should be fine for most of the projects, there *might* be projects where a lot of references are created (e.g. if every function parameters are indexed in a veeeeery large library, we might hit the limit somehow).

File: sphinx/themes/basic/static/searchtools.js [hunk 4]
```diff
@@ -137,6 +137,18 @@ const _displayNextItem = (
   // search finished, update title and status message
   else _finishSearch(resultCount);
 };
+const _orderResultsByScoreThenName = (a, b) => {
```
Comment (picnixz) [inline sphinx/themes/basic/static/searchtools.js:144]: It would be good to add a comment on where this function is used, what it does and what would be the layout of a and b.

**Comment by bradking** [comment]
I added a merge commit to resolve conflicts with `master`.  Please let me know if I should rebase instead.

**Comment by picnixz** [comment]
I think it's fine since we squash the commits at the end.

**Comment by picnixz** [comment]
I'll review it by the end of this weekend. Seems fine for me though (but @AA-Turner should review as well). By the way, could the OP confirm that this PR will not break existing projects. Like, is it sure that nonmain index entries are really irrelevant compared to main ones in general?

File: sphinx/themes/basic/static/searchtools.js [hunk 5]
```diff
@@ -137,6 +137,22 @@ const _displayNextItem = (
   // search finished, update title and status message
   else _finishSearch(resultCount);
 };
+// Helper function used by query() to order search results.
+// Each input is an array of [docname, title, anchor, descr, score, filename].
+// Order the results by score (in opposite order of appearance, since the
+// display function below uses pop() to retrieve items) and then alphabetically.
```
Comment (picnixz) [inline sphinx/themes/basic/static/searchtools.js]:
```suggestion
// `_displayNextItem` function uses pop() to retrieve items) and then alphabetically.
```

**Review by picnixz — COMMENTED** [review]
For me it's fine. But could I know its real effect on existing projects such as the Python docs (compared to the original issue where we introduced this search). Also, did it actually fix the CMake documentation?

**Comment by bradking** [comment]
> this PR will not break existing project? Like, is it ensured that nonmain index entries are really irrelevant compared to main ones in general?

AFAICT the original motivation was only for main entries.  #6692 requests support for the "index directive".  Review of #10819 did not raise the distinction.

> did it actually fix the CMake documentation?

Yes.  That's what's motivating this PR.

**Review by picnixz — APPROVED** [review]
Ah sorry! as I said on another post, I am quite unable to review anything. However, if everything works well for both CMake and Python, then I have nothing more to 

By the way, I don't have any write access and we usually wait for Adam's reviews before merging (sometimes, I miss obvious issues) but since they're also busy, I don't know when this will be reviewed.

**Comment by bradking** [comment]
@picnixz @AA-Turner I've updated this PR to resolve conflicts with master.  Please review again.

**Comment by picnixz** [comment]
Errr.. for me it's fine? I mean, I don't think there has been any difference with what I've already reviewed and the fact that no changes should occur with CMake and Python is a good indication. Since I'm only passing by, I don't want to merge now (if there's an issue afterwards, I won't be able to react fast enough) so I'll let @AA-Turner have a look as well.

**Comment by picnixz** [comment]
I think it's better if we don't wait too long for that one. I'll endorse the merge (just resolve the conflicts and we're good to go).

**Comment by picnixz** [comment]
Thank you!
