### PR TITLE
Do not run `window.history.replaceState` unconditionally

### LINKED ISSUE #13916: `sphinx_highlight.js` removes text fragment from URL
### Describe the bug

All major browsers support highlighting with [Text Fragments](https://developer.mozilla.org/en-US/docs/Web/URI/Reference/Fragment/Text_fragments), which is the `#:~:text=...` bit in a URL:

https://www.sphinx-doc.org/en/master/usage/quickstart.html#:~:text=In%20Sphinx%20source

It highlights and scrolls to the first match on the page, which is extremely useful. It's used by Google Search to scroll to a particular part of the page, and by LLMs to link to a relevant bit of the page they got their answers from, which is super useful these days.

Annoyingly, Sphinx's `sphinx_highlight.js` always removes this text fragment from the URL, making sharing of the exact URL the user found impossible.

### How to Reproduce

Go to

https://www.sphinx-doc.org/en/master/usage/quickstart.html#:~:text=In%20Sphinx%20source

Notice that the URL bar is immediately replaced with

```
https://www.sphinx-doc.org/en/master/usage/quickstart.html
```

instead of the original

```
https://www.sphinx-doc.org/en/master/usage/quickstart.html#:~:text=In%20Sphinx%20source
```

Presumably this is due to 

https://github.com/sphinx-doc/sphinx/blob/eaebbec4d165efcb5048fc06431e3bf796c9d224/sphinx/themes/basic/static/sphinx_highlight.js#L84

which is run unconditionally from

https://github.com/sphinx-doc/sphinx/blob/eaebbec4d165efcb5048fc06431e3bf796c9d224/sphinx/themes/basic/static/sphinx_highlight.js#L153

### PR DESCRIPTION
**Pull request by haampie**
Closes #13916 

Currently every Sphinx documentation page *always* drops `#:~:text=...` [Text Fragments](https://developer.mozilla.org/en-US/docs/Web/URI/Reference/Fragment/Text_fragments) due to an unconditional `window.history.replaceState()` call. That `replaceState()` is almost always redundant, since it happens when handling `?highlight=...` search term highlighting, which is rarely present in the URL.

It's undesirable, because it prevents users from sharing the URL verbatim including the text fragment from the browser's URL bar. Text fragments are increasingly popular these days as they're used by Google Search and various LLMs to scroll to and highlight specific content on a longer page.

The solution is to only call `window.history.replaceState` when a Sphinx's custom `?highlight=...` search param is part of the URL.

### CODE REVIEW

**Comment by jayaddison** [comment]
For this pull request and/or #13921, please add an entry in the [`CHANGES.rst` file](https://github.com/sphinx-doc/sphinx/blob/b9d5d2bacca83edcd6f7cb10c63490ec1b29fccd/CHANGES.rst?plain=1) -- perhaps at the end of either the [bugfix list](https://github.com/sphinx-doc/sphinx/blob/b9d5d2bacca83edcd6f7cb10c63490ec1b29fccd/CHANGES.rst?plain=1#L140) or [features list](https://github.com/sphinx-doc/sphinx/blob/b9d5d2bacca83edcd6f7cb10c63490ec1b29fccd/CHANGES.rst?plain=1#L71), as appropriate, with a description of the modifications and a credit entry.

**Comment by haampie** [comment]
@jayaddison, I've added it to CHANGES.rst.

Since #13921 seems to be blocked, I'd suggest to go with this minimal bug fix.

Is the CI failure expected? Looks unrelated.

**Review by jayaddison — APPROVED** [review]
@haampie thanks for being patient - this looks good to me, and I have tested it locally to confirm the before-and-after behaviours.

I agree that the 1-out-of-30 GitHub Actions check failure (unit tests) seems to be an unrelated issue - we'd welcome a bug report (similar to #12159 for example) if you have time -- I'll try to get around to reporting that within the next week or so otherwise.

**Comment by haampie** [comment]
Looks like an issue was already opened a couple weeks ago: https://github.com/sphinx-doc/sphinx/issues/13996

**Comment by haampie** [comment]
@jayaddison closed and opened the PR to restart github actions, which are now green. So the PR should be good to go.

**Comment by jayaddison** [comment]
Thanks @haampie - I'm a contributor here, but I am not a core developer/maintainer, so I don't have permissions to merge.  We'll need to wait/find one of the core team to help with that (they do check recently opened PRs from time to time; I can't guarantee how long it may take, though).

**Comment by haampie** [comment]
Maybe a friendly ping to @mgeier helps? For context, this PR should not be controversial, in contrast to #13921.

It fixes a bug where the browser clears parts `#...` bit of the URL on page load, even if there is no `?highlight=...` param. Now it only does that when there is a highlight param.

**Review by mgeier — APPROVED** [review]

**Comment by mgeier** [comment]
I'm not a core dev either. I approve, but someone else will have to merge it.

**Comment by haampie** [comment]
In that case a friendly ping for @AA-Turner for a potential merge, since this PR has fallen of the first PRs page.

**Review by AA-Turner — COMMENTED** [review]
Please can you add a comment explaining why we don't unconditionally run the code. If possible, adding a test would also be great.

A

**Comment by haampie** [comment]
I've added a comment, which I think is enough. There are no existing tests covering that part.

File: sphinx/themes/basic/static/sphinx_highlight.js [hunk 1]
```diff
@@ -80,8 +80,12 @@ const SphinxHighlight = {
       || url.searchParams.get("highlight")
       || "";
     localStorage.removeItem("sphinx_highlight_terms");
-    url.searchParams.delete("highlight");
-    window.history.replaceState({}, "", url);
+    // run replaceState only if "highlight" is present; otherwise it
+    // clears text fragments (not set in window.location by the browser)
```
Comment (AA-Turner) [inline sphinx/themes/basic/static/sphinx_highlight.js]:
```suggestion
    // Update history only if '?highlight' is present; otherwise it
    // clears text fragments (not set in window.location by the browser)
```

**Review by AA-Turner — APPROVED** [review]

**Comment by AA-Turner** [comment]
Thanks!

A
